// This file is auto-generated by @hey-api/openapi-ts

/**
 * Critere
 */
export type Critere = {
    libelleCourt?: string;
    libelleLong?: string;
    regleChamp?: string;
};

/**
 * CustomPageOfDeclarationDTO
 */
export type CustomPageOfDeclarationDto = {
    hits?: Hits;
    result?: Array<DeclarationDto>;
};

/**
 * CustomPageOfFestivalDTO
 */
export type CustomPageOfFestivalDto = {
    hits?: Hits;
    result?: Array<FestivalDto>;
};

/**
 * CustomPageOfLieuDTO
 */
export type CustomPageOfLieuDto = {
    hits?: Hits;
    result?: Array<LieuDto>;
};

/**
 * CustomPageOfSpectacleDTO
 */
export type CustomPageOfSpectacleDto = {
    hits?: Hits;
    result?: Array<SpectacleDto>;
};

/**
 * DeclarationDTO
 */
export type DeclarationDto = {
    codeErreur?: string;
    dateCreation?: string;
    dateDebut?: string;
    dateFin?: string;
    dateHeureRepresentationUnique?: string;
    dateModification?: string;
    declarantId?: number;
    demandeurId?: number;
    demandeurLogin?: string;
    departement?: string;
    domaineRepresentationId?: number;
    domaineRepresentationLibelle?: string;
    festivalChamps?: FestivalDto;
    festivalId?: number;
    festivalNom?: string;
    gestionnaireMultiple?: boolean;
    id?: number;
    idExtBilletterie?: string;
    jauge?: number;
    jeunePublic?: boolean;
    lieuChamps?: LieuDto;
    lieuId?: number;
    lieuNom?: string;
    nbBilletsExoneres?: number;
    nbBilletsTarifAbonnementForfait?: number;
    nbBilletsTarifPlein?: number;
    nbBilletsTotalBilletterie?: number;
    nbRepresentations?: number;
    nomJuridiqueOrganismeDeclarant?: string;
    prixMoyenTarifPlein?: number;
    prixMoyenTotalBilletterie?: number;
    recetteTarifPlein?: number;
    recetteTotalBilletterie?: number;
    region?: string;
    role?: string;
    spectacleChamps?: SpectacleDto;
    spectacleCritere1?: string;
    spectacleId?: number;
    statutDeclaration?: 'BROUILLON' | 'ENREGISTRE' | 'CLOTURE' | 'REJETE' | 'ANNULE';
    valide?: boolean;
    version?: number;
};

/**
 * DomaineConfig
 */
export type DomaineConfig = {
    critere1?: Critere;
    critere2?: Critere;
    critere3?: Critere;
    critere4?: Critere;
    domaineId?: string;
    domaineLibelle?: string;
};

/**
 * DomaineRepresentationDTO
 */
export type DomaineRepresentationDto = {
    actif?: boolean;
    dateCreation?: string;
    dateModification?: string;
    id?: number;
    libelle: string;
    libelleTri?: string;
    libelleV1?: string;
};

/**
 * EnumDTO
 */
export type EnumDto = {
    code?: string;
    value?: string;
};

/**
 * FestivalDTO
 */
export type FestivalDto = {
    codError?: string;
    codePostal: string;
    contributeurId?: number;
    contributeurLogin?: string;
    dateCreation?: string;
    dateModification?: string;
    domaineFestivalId?: number;
    domaineFestivalLibelle?: string;
    id?: number;
    nom: string;
    parentId?: number;
    parentNom?: string;
    statut?: 'PROPOSE' | 'VALIDE' | 'REJETE' | 'FUSIONNE';
    validateurId?: number;
    validateurLogin?: string;
    validationApiExterne?: boolean;
    ville: string;
};

/**
 * Hits
 */
export type Hits = {
    maxResult?: number;
    page?: number;
    pageLimit?: number;
    size?: number;
    total?: number;
};

/**
 * ImportCSVDTO
 */
export type ImportCsvdto = {
    countErr?: number;
    countSuccess?: number;
    countTot?: number;
    errorsDetails?: Array<ImportErrorDetail>;
};

/**
 * ImportErrorDetail
 */
export type ImportErrorDetail = {
    errorDesc?: string;
    errorLine?: number;
    errorNom?: string;
};

/**
 * JWTToken
 */
export type JwtToken = {
    id_token?: string;
    typeError?: string;
    versions?: Array<string>;
};

/**
 * LieuDTO
 */
export type LieuDto = {
    adresse: string;
    codError?: string;
    codePostal: string;
    contributeurId?: number;
    contributeurLogin?: string;
    dateCreation?: string;
    dateModification?: string;
    denominationUsuelle?: string;
    departementCode?: string;
    departementId?: number;
    departementLibelle?: string;
    id?: number;
    nom: string;
    parentId?: number;
    parentNom?: string;
    siret?: string;
    statut?: 'PROPOSE' | 'VALIDE' | 'REJETE' | 'FUSIONNE';
    typeLieu: 'THEATRE' | 'ESPACE_POLYVALENT' | 'CASINO_DISCOTHEQUE_HOTEL_CAFE_RESTAURANT' | 'SALLE_CONCERT_AUDITORIUM_OPERA_ZENITH' | 'CABARET_MUSIC_HALL' | 'PLEIN_AIR_PARC_LOISIRS_ATTRACTION' | 'STRUCTURE_ITINERANTE_DEMONTABLE_CHAPITEAU' | 'LIEU_DE_CULTE' | 'LIEU_DE_SANTE' | 'AUTRE';
    validateurId?: number;
    validateurLogin?: string;
    validationApiExterne?: boolean;
    ville: string;
};

/**
 * LoginVM
 */
export type LoginVm = {
    accessType?: string;
    password: string;
    rememberMe?: boolean;
    username: string;
};

/**
 * RelanceNonConformiteDemandeurDTO
 */
export type RelanceNonConformiteDemandeurDto = {
    authorities?: Array<string>;
    dateCreation: string;
    declarantId?: number;
    demandeurId?: number;
    demandeurLogin?: string;
    id?: number;
    nbDeclarationsNonConforme?: number;
    nomJuridiqueOrganismeDeclarant?: string;
    typeRelance: 'BROUILLON' | 'INVALIDE';
    typeStructure?: TypeStructure;
};

/**
 * SpectacleDTO
 */
export type SpectacleDto = {
    codError?: string;
    contributeurId?: number;
    contributeurLogin?: string;
    critere1?: string;
    critere2?: string;
    critere3?: string;
    critere4?: string;
    dateCreation?: string;
    dateModification?: string;
    domaineSpectacleId?: number;
    domaineSpectacleLibelle?: string;
    id?: number;
    nombreDenfants?: number;
    parentId?: number;
    parentNom?: string;
    statut?: 'PROPOSE' | 'VALIDE' | 'REJETE' | 'FUSIONNE';
    validateurId?: number;
    validateurLogin?: string;
};

/**
 * SpectacleFieldsConfig
 */
export type SpectacleFieldsConfig = {
    domaineConfig?: DomaineConfig;
    idDomaineRepresentation?: number;
};

/**
 * TypeStructure
 */
export type TypeStructure = {
    actif: boolean;
    dateCreation: string;
    id?: number;
    libelle: string;
    parent?: TypeStructure;
    typeStructureTri?: string;
};

export type AuthorizeUsingPostData = {
    /**
     * loginVM
     */
    body: LoginVm;
    path?: never;
    query?: never;
    url: '/api/v2/authenticate';
};

export type AuthorizeUsingPostErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type AuthorizeUsingPostResponses = {
    /**
     * OK
     */
    200: JwtToken;
    /**
     * Created
     */
    201: unknown;
};

export type AuthorizeUsingPostResponse = AuthorizeUsingPostResponses[keyof AuthorizeUsingPostResponses];

export type GetAllDeclarationsUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        'id.in'?: Array<number>;
        'id.equals'?: number;
        'id.specified'?: boolean;
        'id.greaterThan'?: number;
        'id.lessThan'?: number;
        'id.greaterOrEqualThan'?: number;
        'id.lessOrEqualThan'?: number;
        'idExtBilletterie.in'?: Array<string>;
        'idExtBilletterie.equals'?: string;
        'idExtBilletterie.specified'?: boolean;
        'idExtBilletterie.contains'?: string;
        'statutDeclaration.in'?: 'BROUILLON' | 'ENREGISTRE' | 'CLOTURE' | 'REJETE' | 'ANNULE';
        'statutDeclaration.equals'?: string;
        'statutDeclaration.specified'?: boolean;
        'spectacleId.in'?: Array<number>;
        'spectacleId.equals'?: number;
        'spectacleId.specified'?: boolean;
        'spectacleId.greaterThan'?: number;
        'spectacleId.lessThan'?: number;
        'spectacleId.greaterOrEqualThan'?: number;
        'spectacleId.lessOrEqualThan'?: number;
        'spectacleCritere1.in'?: Array<string>;
        'spectacleCritere1.equals'?: string;
        'spectacleCritere1.specified'?: boolean;
        'spectacleCritere1.contains'?: string;
        'festivalId.in'?: Array<number>;
        'festivalId.equals'?: number;
        'festivalId.specified'?: boolean;
        'festivalId.greaterThan'?: number;
        'festivalId.lessThan'?: number;
        'festivalId.greaterOrEqualThan'?: number;
        'festivalId.lessOrEqualThan'?: number;
        'festivalNom.in'?: Array<string>;
        'festivalNom.equals'?: string;
        'festivalNom.specified'?: boolean;
        'festivalNom.contains'?: string;
        'declarantId.in'?: Array<number>;
        'declarantId.equals'?: number;
        'declarantId.specified'?: boolean;
        'declarantId.greaterThan'?: number;
        'declarantId.lessThan'?: number;
        'declarantId.greaterOrEqualThan'?: number;
        'declarantId.lessOrEqualThan'?: number;
        'nomJuridiqueOrganismeDeclarant.in'?: Array<string>;
        'nomJuridiqueOrganismeDeclarant.equals'?: string;
        'nomJuridiqueOrganismeDeclarant.specified'?: boolean;
        'nomJuridiqueOrganismeDeclarant.contains'?: string;
        'lieuId.in'?: Array<number>;
        'lieuId.equals'?: number;
        'lieuId.specified'?: boolean;
        'lieuId.greaterThan'?: number;
        'lieuId.lessThan'?: number;
        'lieuId.greaterOrEqualThan'?: number;
        'lieuId.lessOrEqualThan'?: number;
        'lieuNom.in'?: Array<string>;
        'lieuNom.equals'?: string;
        'lieuNom.specified'?: boolean;
        'lieuNom.contains'?: string;
        'demandeurId.in'?: Array<number>;
        'demandeurId.equals'?: number;
        'demandeurId.specified'?: boolean;
        'demandeurId.greaterThan'?: number;
        'demandeurId.lessThan'?: number;
        'demandeurId.greaterOrEqualThan'?: number;
        'demandeurId.lessOrEqualThan'?: number;
        'demandeurLogin.in'?: Array<string>;
        'demandeurLogin.equals'?: string;
        'demandeurLogin.specified'?: boolean;
        'demandeurLogin.contains'?: string;
        'domaineRepresentationId.in'?: Array<number>;
        'domaineRepresentationId.equals'?: number;
        'domaineRepresentationId.specified'?: boolean;
        'domaineRepresentationId.greaterThan'?: number;
        'domaineRepresentationId.lessThan'?: number;
        'domaineRepresentationId.greaterOrEqualThan'?: number;
        'domaineRepresentationId.lessOrEqualThan'?: number;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.in'?: Array<string>;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.equals'?: string;
        'dateCreation.specified'?: boolean;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateModification.in'?: Array<string>;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateModification.greaterThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateModification.lessThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateModification.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateModification.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateModification.equals'?: string;
        'dateModification.specified'?: boolean;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateHeureRepresentationUnique.in'?: Array<string>;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateHeureRepresentationUnique.greaterThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateHeureRepresentationUnique.lessThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateHeureRepresentationUnique.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateHeureRepresentationUnique.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateHeureRepresentationUnique.equals'?: string;
        'dateHeureRepresentationUnique.specified'?: boolean;
        /**
         * format "yyyy-MM-dd"
         */
        'dateDebut.in'?: Array<string>;
        /**
         * format "yyyy-MM-dd"
         */
        'dateDebut.greaterThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateDebut.lessThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateDebut.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateDebut.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateDebut.equals'?: string;
        'dateDebut.specified'?: boolean;
        /**
         * format "yyyy-MM-dd"
         */
        'dateFin.in'?: Array<string>;
        /**
         * format "yyyy-MM-dd"
         */
        'dateFin.greaterThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateFin.lessThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateFin.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateFin.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-dd"
         */
        'dateFin.equals'?: string;
        'dateFin.specified'?: boolean;
        andOr?: boolean;
        /**
         * format "yyyy-MM-dd"
         */
        dateStart?: string;
        /**
         * format "yyyy-MM-dd"
         */
        dateEnd?: string;
    };
    url: '/api/v2/declarations';
};

export type GetAllDeclarationsUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllDeclarationsUsingGet1Responses = {
    /**
     * OK
     */
    200: CustomPageOfDeclarationDto;
};

export type GetAllDeclarationsUsingGet1Response = GetAllDeclarationsUsingGet1Responses[keyof GetAllDeclarationsUsingGet1Responses];

export type CreateDeclarationUsingPost1Data = {
    /**
     * declarationDTO
     */
    body: DeclarationDto;
    path?: never;
    query?: never;
    url: '/api/v2/declarations';
};

export type CreateDeclarationUsingPost1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateDeclarationUsingPost1Responses = {
    /**
     * OK
     */
    200: DeclarationDto;
    /**
     * Created
     */
    201: unknown;
};

export type CreateDeclarationUsingPost1Response = CreateDeclarationUsingPost1Responses[keyof CreateDeclarationUsingPost1Responses];

export type UpdateDeclarationUsingPut1Data = {
    /**
     * declarationDTO
     */
    body: DeclarationDto;
    path?: never;
    query?: never;
    url: '/api/v2/declarations';
};

export type UpdateDeclarationUsingPut1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateDeclarationUsingPut1Responses = {
    /**
     * OK
     */
    200: DeclarationDto;
    /**
     * Created
     */
    201: unknown;
};

export type UpdateDeclarationUsingPut1Response = UpdateDeclarationUsingPut1Responses[keyof UpdateDeclarationUsingPut1Responses];

export type ImportDeclarationsCsvUsingPostData = {
    body: {
        /**
         * declarationCSV
         */
        declarationCSV: Blob | File;
    };
    path?: never;
    query?: {
        /**
         * declarantId
         */
        declarantId?: number;
    };
    url: '/api/v2/declarations/importCsv';
};

export type ImportDeclarationsCsvUsingPostErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type ImportDeclarationsCsvUsingPostResponses = {
    /**
     * OK
     */
    200: ImportCsvdto;
    /**
     * Created
     */
    201: unknown;
};

export type ImportDeclarationsCsvUsingPostResponse = ImportDeclarationsCsvUsingPostResponses[keyof ImportDeclarationsCsvUsingPostResponses];

export type DeleteDeclarationUsingDelete1Data = {
    body?: never;
    path: {
        /**
         * id
         */
        id: string;
    };
    query?: never;
    url: '/api/v2/declarations/{id}';
};

export type DeleteDeclarationUsingDelete1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteDeclarationUsingDelete1Responses = {
    /**
     * OK
     */
    200: unknown;
    /**
     * No Content
     */
    204: unknown;
};

export type GetDeclarationUsingGet1Data = {
    body?: never;
    path: {
        /**
         * id
         */
        id: string;
    };
    query?: never;
    url: '/api/v2/declarations/{id}';
};

export type GetDeclarationUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetDeclarationUsingGet1Responses = {
    /**
     * OK
     */
    200: DeclarationDto;
};

export type GetDeclarationUsingGet1Response = GetDeclarationUsingGet1Responses[keyof GetDeclarationUsingGet1Responses];

export type GetAllDomaineRepresentationsUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * actif
         */
        actif?: boolean;
        /**
         * sansPagination
         */
        sansPagination?: boolean;
    };
    url: '/api/v2/domaine-representations';
};

export type GetAllDomaineRepresentationsUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllDomaineRepresentationsUsingGet1Responses = {
    /**
     * OK
     */
    200: Array<DomaineRepresentationDto>;
};

export type GetAllDomaineRepresentationsUsingGet1Response = GetAllDomaineRepresentationsUsingGet1Responses[keyof GetAllDomaineRepresentationsUsingGet1Responses];

export type GetDomaineRepresentationUsingGet1Data = {
    body?: never;
    path: {
        /**
         * id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2/domaine-representations/{id}';
};

export type GetDomaineRepresentationUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetDomaineRepresentationUsingGet1Responses = {
    /**
     * OK
     */
    200: DomaineRepresentationDto;
};

export type GetDomaineRepresentationUsingGet1Response = GetDomaineRepresentationUsingGet1Responses[keyof GetDomaineRepresentationUsingGet1Responses];

export type GetAllFestivalsUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        'id.in'?: Array<number>;
        'id.equals'?: number;
        'id.specified'?: boolean;
        'id.greaterThan'?: number;
        'id.lessThan'?: number;
        'id.greaterOrEqualThan'?: number;
        'id.lessOrEqualThan'?: number;
        'nom.in'?: Array<string>;
        'nom.equals'?: string;
        'nom.specified'?: boolean;
        'nom.contains'?: string;
        'codePostal.in'?: Array<string>;
        'codePostal.equals'?: string;
        'codePostal.specified'?: boolean;
        'codePostal.contains'?: string;
        'ville.in'?: Array<string>;
        'ville.equals'?: string;
        'ville.specified'?: boolean;
        'ville.contains'?: string;
        'statut.in'?: 'PROPOSE' | 'VALIDE' | 'REJETE' | 'FUSIONNE';
        'statut.equals'?: string;
        'statut.specified'?: boolean;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.in'?: Array<string>;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.equals'?: string;
        'dateCreation.specified'?: boolean;
        'contributeurId.in'?: Array<number>;
        'contributeurId.equals'?: number;
        'contributeurId.specified'?: boolean;
        'contributeurId.greaterThan'?: number;
        'contributeurId.lessThan'?: number;
        'contributeurId.greaterOrEqualThan'?: number;
        'contributeurId.lessOrEqualThan'?: number;
        'validateurId.in'?: Array<number>;
        'validateurId.equals'?: number;
        'validateurId.specified'?: boolean;
        'validateurId.greaterThan'?: number;
        'validateurId.lessThan'?: number;
        'validateurId.greaterOrEqualThan'?: number;
        'validateurId.lessOrEqualThan'?: number;
        'validateur.in'?: Array<string>;
        'validateur.equals'?: string;
        'validateur.specified'?: boolean;
        'validateur.contains'?: string;
        'contributeur.in'?: Array<string>;
        'contributeur.equals'?: string;
        'contributeur.specified'?: boolean;
        'contributeur.contains'?: string;
        andOr?: boolean;
        /**
         * format "yyyy-MM-dd"
         */
        dateStart?: string;
        /**
         * format "yyyy-MM-dd"
         */
        dateEnd?: string;
    };
    url: '/api/v2/festivals';
};

export type GetAllFestivalsUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllFestivalsUsingGet1Responses = {
    /**
     * OK
     */
    200: CustomPageOfFestivalDto;
};

export type GetAllFestivalsUsingGet1Response = GetAllFestivalsUsingGet1Responses[keyof GetAllFestivalsUsingGet1Responses];

export type CreateFestivalUsingPost1Data = {
    /**
     * festivalDTO
     */
    body: FestivalDto;
    path?: never;
    query?: never;
    url: '/api/v2/festivals';
};

export type CreateFestivalUsingPost1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateFestivalUsingPost1Responses = {
    /**
     * OK
     */
    200: FestivalDto;
    /**
     * Created
     */
    201: unknown;
};

export type CreateFestivalUsingPost1Response = CreateFestivalUsingPost1Responses[keyof CreateFestivalUsingPost1Responses];

export type FestivalFullTextSearchUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * value
         */
        value: string;
    };
    url: '/api/v2/festivals/fulltext';
};

export type FestivalFullTextSearchUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type FestivalFullTextSearchUsingGetResponses = {
    /**
     * OK
     */
    200: CustomPageOfFestivalDto;
};

export type FestivalFullTextSearchUsingGetResponse = FestivalFullTextSearchUsingGetResponses[keyof FestivalFullTextSearchUsingGetResponses];

export type FestivalIndexedFullTextSearchUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * recherche
         */
        recherche: string;
    };
    url: '/api/v2/festivals/indexedFulltext';
};

export type FestivalIndexedFullTextSearchUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type FestivalIndexedFullTextSearchUsingGetResponses = {
    /**
     * OK
     */
    200: CustomPageOfFestivalDto;
};

export type FestivalIndexedFullTextSearchUsingGetResponse = FestivalIndexedFullTextSearchUsingGetResponses[keyof FestivalIndexedFullTextSearchUsingGetResponses];

export type GetFestivalUsingGetData = {
    body?: never;
    path: {
        /**
         * id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2/festivals/{id}';
};

export type GetFestivalUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetFestivalUsingGetResponses = {
    /**
     * OK
     */
    200: FestivalDto;
};

export type GetFestivalUsingGetResponse = GetFestivalUsingGetResponses[keyof GetFestivalUsingGetResponses];

export type GetAllLieuxUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        'id.in'?: Array<number>;
        'id.equals'?: number;
        'id.specified'?: boolean;
        'id.greaterThan'?: number;
        'id.lessThan'?: number;
        'id.greaterOrEqualThan'?: number;
        'id.lessOrEqualThan'?: number;
        'nom.in'?: Array<string>;
        'nom.equals'?: string;
        'nom.specified'?: boolean;
        'nom.contains'?: string;
        'codePostal.in'?: Array<string>;
        'codePostal.equals'?: string;
        'codePostal.specified'?: boolean;
        'codePostal.contains'?: string;
        'ville.in'?: Array<string>;
        'ville.equals'?: string;
        'ville.specified'?: boolean;
        'ville.contains'?: string;
        'adresse.in'?: Array<string>;
        'adresse.equals'?: string;
        'adresse.specified'?: boolean;
        'adresse.contains'?: string;
        'siret.in'?: Array<string>;
        'siret.equals'?: string;
        'siret.specified'?: boolean;
        'siret.contains'?: string;
        'typeLieu.in'?: 'THEATRE' | 'ESPACE_POLYVALENT' | 'CASINO_DISCOTHEQUE_HOTEL_CAFE_RESTAURANT' | 'SALLE_CONCERT_AUDITORIUM_OPERA_ZENITH' | 'CABARET_MUSIC_HALL' | 'PLEIN_AIR_PARC_LOISIRS_ATTRACTION' | 'STRUCTURE_ITINERANTE_DEMONTABLE_CHAPITEAU' | 'LIEU_DE_CULTE' | 'LIEU_DE_SANTE' | 'AUTRE';
        'typeLieu.equals'?: string;
        'typeLieu.specified'?: boolean;
        'statut.in'?: 'PROPOSE' | 'VALIDE' | 'REJETE' | 'FUSIONNE';
        'statut.equals'?: string;
        'statut.specified'?: boolean;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.in'?: Array<string>;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.equals'?: string;
        'dateCreation.specified'?: boolean;
        'contributeurId.in'?: Array<number>;
        'contributeurId.equals'?: number;
        'contributeurId.specified'?: boolean;
        'contributeurId.greaterThan'?: number;
        'contributeurId.lessThan'?: number;
        'contributeurId.greaterOrEqualThan'?: number;
        'contributeurId.lessOrEqualThan'?: number;
        'validateurId.in'?: Array<number>;
        'validateurId.equals'?: number;
        'validateurId.specified'?: boolean;
        'validateurId.greaterThan'?: number;
        'validateurId.lessThan'?: number;
        'validateurId.greaterOrEqualThan'?: number;
        'validateurId.lessOrEqualThan'?: number;
        'validateur.in'?: Array<string>;
        'validateur.equals'?: string;
        'validateur.specified'?: boolean;
        'validateur.contains'?: string;
        'contributeur.in'?: Array<string>;
        'contributeur.equals'?: string;
        'contributeur.specified'?: boolean;
        'contributeur.contains'?: string;
        'denominationUsuelle.in'?: Array<string>;
        'denominationUsuelle.equals'?: string;
        'denominationUsuelle.specified'?: boolean;
        'denominationUsuelle.contains'?: string;
        andOr?: boolean;
        /**
         * format "yyyy-MM-dd"
         */
        dateStart?: string;
        /**
         * format "yyyy-MM-dd"
         */
        dateEnd?: string;
    };
    url: '/api/v2/lieux';
};

export type GetAllLieuxUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllLieuxUsingGet1Responses = {
    /**
     * OK
     */
    200: CustomPageOfLieuDto;
};

export type GetAllLieuxUsingGet1Response = GetAllLieuxUsingGet1Responses[keyof GetAllLieuxUsingGet1Responses];

export type CreateLieuUsingPost1Data = {
    /**
     * lieuDTO
     */
    body: LieuDto;
    path?: never;
    query?: never;
    url: '/api/v2/lieux';
};

export type CreateLieuUsingPost1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateLieuUsingPost1Responses = {
    /**
     * OK
     */
    200: LieuDto;
    /**
     * Created
     */
    201: unknown;
};

export type CreateLieuUsingPost1Response = CreateLieuUsingPost1Responses[keyof CreateLieuUsingPost1Responses];

export type LieuFullTextSearchUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * value
         */
        value: string;
    };
    url: '/api/v2/lieux/fulltext';
};

export type LieuFullTextSearchUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type LieuFullTextSearchUsingGetResponses = {
    /**
     * OK
     */
    200: CustomPageOfLieuDto;
};

export type LieuFullTextSearchUsingGetResponse = LieuFullTextSearchUsingGetResponses[keyof LieuFullTextSearchUsingGetResponses];

export type LieuIndexedFullTextSearchUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * recherche
         */
        recherche: string;
    };
    url: '/api/v2/lieux/indexedFulltext';
};

export type LieuIndexedFullTextSearchUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type LieuIndexedFullTextSearchUsingGetResponses = {
    /**
     * OK
     */
    200: CustomPageOfLieuDto;
};

export type LieuIndexedFullTextSearchUsingGetResponse = LieuIndexedFullTextSearchUsingGetResponses[keyof LieuIndexedFullTextSearchUsingGetResponses];

export type GetAllTypesLieuUsingGet1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/lieux/types';
};

export type GetAllTypesLieuUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllTypesLieuUsingGet1Responses = {
    /**
     * OK
     */
    200: Array<EnumDto>;
};

export type GetAllTypesLieuUsingGet1Response = GetAllTypesLieuUsingGet1Responses[keyof GetAllTypesLieuUsingGet1Responses];

export type SearchByLieuTypeUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * value
         */
        value: string;
    };
    url: '/api/v2/lieux/types/search';
};

export type SearchByLieuTypeUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SearchByLieuTypeUsingGetResponses = {
    /**
     * OK
     */
    200: Array<EnumDto>;
};

export type SearchByLieuTypeUsingGetResponse = SearchByLieuTypeUsingGetResponses[keyof SearchByLieuTypeUsingGetResponses];

export type GetLieuUsingGetData = {
    body?: never;
    path: {
        /**
         * id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2/lieux/{id}';
};

export type GetLieuUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetLieuUsingGetResponses = {
    /**
     * OK
     */
    200: LieuDto;
};

export type GetLieuUsingGetResponse = GetLieuUsingGetResponses[keyof GetLieuUsingGetResponses];

export type GetRelanceUsingGetData = {
    body?: never;
    path: {
        /**
         * id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2/relances/{id}';
};

export type GetRelanceUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRelanceUsingGetResponses = {
    /**
     * OK
     */
    200: Array<RelanceNonConformiteDemandeurDto>;
};

export type GetRelanceUsingGetResponse = GetRelanceUsingGetResponses[keyof GetRelanceUsingGetResponses];

export type GetAllSpectaclesUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        'id.in'?: Array<number>;
        'id.equals'?: number;
        'id.specified'?: boolean;
        'id.greaterThan'?: number;
        'id.lessThan'?: number;
        'id.greaterOrEqualThan'?: number;
        'id.lessOrEqualThan'?: number;
        'critere1.in'?: Array<string>;
        'critere1.equals'?: string;
        'critere1.specified'?: boolean;
        'critere1.contains'?: string;
        'critere2.in'?: Array<string>;
        'critere2.equals'?: string;
        'critere2.specified'?: boolean;
        'critere2.contains'?: string;
        'critere3.in'?: Array<string>;
        'critere3.equals'?: string;
        'critere3.specified'?: boolean;
        'critere3.contains'?: string;
        'critere4.in'?: Array<string>;
        'critere4.equals'?: string;
        'critere4.specified'?: boolean;
        'critere4.contains'?: string;
        'statut.in'?: 'PROPOSE' | 'VALIDE' | 'REJETE' | 'FUSIONNE';
        'statut.equals'?: string;
        'statut.specified'?: boolean;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.in'?: Array<string>;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.greaterOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.lessOrEqualThan'?: string;
        /**
         * format "yyyy-MM-ddTHH:mm:ss.SSSZ"
         */
        'dateCreation.equals'?: string;
        'dateCreation.specified'?: boolean;
        'contributeurId.in'?: Array<number>;
        'contributeurId.equals'?: number;
        'contributeurId.specified'?: boolean;
        'contributeurId.greaterThan'?: number;
        'contributeurId.lessThan'?: number;
        'contributeurId.greaterOrEqualThan'?: number;
        'contributeurId.lessOrEqualThan'?: number;
        'contributeur.in'?: Array<string>;
        'contributeur.equals'?: string;
        'contributeur.specified'?: boolean;
        'contributeur.contains'?: string;
        'validateurId.in'?: Array<number>;
        'validateurId.equals'?: number;
        'validateurId.specified'?: boolean;
        'validateurId.greaterThan'?: number;
        'validateurId.lessThan'?: number;
        'validateurId.greaterOrEqualThan'?: number;
        'validateurId.lessOrEqualThan'?: number;
        'validateur.in'?: Array<string>;
        'validateur.equals'?: string;
        'validateur.specified'?: boolean;
        'validateur.contains'?: string;
        'domaineRepresentationId.in'?: Array<number>;
        'domaineRepresentationId.equals'?: number;
        'domaineRepresentationId.specified'?: boolean;
        'domaineRepresentationId.greaterThan'?: number;
        'domaineRepresentationId.lessThan'?: number;
        'domaineRepresentationId.greaterOrEqualThan'?: number;
        'domaineRepresentationId.lessOrEqualThan'?: number;
        andOr?: boolean;
        /**
         * format "yyyy-MM-dd"
         */
        dateStart?: string;
        /**
         * format "yyyy-MM-dd"
         */
        dateEnd?: string;
    };
    url: '/api/v2/spectacles';
};

export type GetAllSpectaclesUsingGet1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllSpectaclesUsingGet1Responses = {
    /**
     * OK
     */
    200: CustomPageOfSpectacleDto;
};

export type GetAllSpectaclesUsingGet1Response = GetAllSpectaclesUsingGet1Responses[keyof GetAllSpectaclesUsingGet1Responses];

export type CreateSpectacleUsingPost1Data = {
    /**
     * spectacleDTO
     */
    body: SpectacleDto;
    path?: never;
    query?: never;
    url: '/api/v2/spectacles';
};

export type CreateSpectacleUsingPost1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateSpectacleUsingPost1Responses = {
    /**
     * OK
     */
    200: SpectacleDto;
    /**
     * Created
     */
    201: unknown;
};

export type CreateSpectacleUsingPost1Response = CreateSpectacleUsingPost1Responses[keyof CreateSpectacleUsingPost1Responses];

export type GetAllConfigChampsUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/spectacles/configChamps';
};

export type GetAllConfigChampsUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAllConfigChampsUsingGetResponses = {
    /**
     * OK
     */
    200: Array<SpectacleFieldsConfig>;
};

export type GetAllConfigChampsUsingGetResponse = GetAllConfigChampsUsingGetResponses[keyof GetAllConfigChampsUsingGetResponses];

export type SpectacleFullTextSearchUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * value
         */
        value: string;
    };
    url: '/api/v2/spectacles/fulltext';
};

export type SpectacleFullTextSearchUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SpectacleFullTextSearchUsingGetResponses = {
    /**
     * OK
     */
    200: CustomPageOfSpectacleDto;
};

export type SpectacleFullTextSearchUsingGetResponse = SpectacleFullTextSearchUsingGetResponses[keyof SpectacleFullTextSearchUsingGetResponses];

export type SpectacleIndexedFullTextSearchUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * recherche
         */
        recherche: string;
    };
    url: '/api/v2/spectacles/indexedFulltext';
};

export type SpectacleIndexedFullTextSearchUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SpectacleIndexedFullTextSearchUsingGetResponses = {
    /**
     * OK
     */
    200: CustomPageOfSpectacleDto;
};

export type SpectacleIndexedFullTextSearchUsingGetResponse = SpectacleIndexedFullTextSearchUsingGetResponses[keyof SpectacleIndexedFullTextSearchUsingGetResponses];

export type GetSpectacleUsingGetData = {
    body?: never;
    path: {
        /**
         * id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2/spectacles/{id}';
};

export type GetSpectacleUsingGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSpectacleUsingGetResponses = {
    /**
     * OK
     */
    200: SpectacleDto;
};

export type GetSpectacleUsingGetResponse = GetSpectacleUsingGetResponses[keyof GetSpectacleUsingGetResponses];

export type ClientOptions = {
    baseUrl: 'https://sibil.stg.cloud.culture.fr/' | (string & {});
};