// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import type { AuthorizeData, AuthorizeResponse, AuthorizeError, GetEventDetailsData, GetEventDetailsResponse, GetEventDetailsError, FindAllShowByEventAndSalesChannelIdData, FindAllShowByEventAndSalesChannelIdResponse, FindAllShowByEventAndSalesChannelIdError, FindAllEventBySalesChannelIdData, FindAllEventBySalesChannelIdResponse, FindAllEventBySalesChannelIdError, FindPricesByShowIdData, FindPricesByShowIdResponse, FindPricesByShowIdError, FindTransactionsData, FindTransactionsResponse, FindTransactionsError, GetEntriesListData, GetEntriesListResponse, GetEntriesListError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

/**
 * Get Token
 * Get bearer access token. This token must be provided in the header of each http request for security reasons.
 */
export const authorize = <ThrowOnError extends boolean = false>(options?: Options<AuthorizeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AuthorizeResponse, AuthorizeError, ThrowOnError>({
        url: '/authorization/token',
        ...options
    });
};

/**
 * Event Details
 * Get event details
 */
export const getEventDetails = <ThrowOnError extends boolean = false>(options: Options<GetEventDetailsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetEventDetailsResponse, GetEventDetailsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/catalog/events/{eventId}',
        ...options
    });
};

/**
 * Shows List
 * Get configured shows for the given event id - An event can consist of one or several shows. Each show has its own set-up and belongs to a single event. If a specified start/end is set, the status is already updated according to these specified datas.
 */
export const findAllShowByEventAndSalesChannelId = <ThrowOnError extends boolean = false>(options: Options<FindAllShowByEventAndSalesChannelIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindAllShowByEventAndSalesChannelIdResponse, FindAllShowByEventAndSalesChannelIdError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/distribution/salesChannels/{salesChannelId}/events/{eventId}/shows',
        ...options
    });
};

/**
 * Products List
 * Get events allocated in current saleschannel - i.e. events that are available for sale on this saleschannel
 */
export const findAllEventBySalesChannelId = <ThrowOnError extends boolean = false>(options: Options<FindAllEventBySalesChannelIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindAllEventBySalesChannelIdResponse, FindAllEventBySalesChannelIdError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/distribution/salesChannels/{salesChannelId}/products',
        ...options
    });
};

/**
 * Prices List
 * Get all prices from a specific show - i.e. For a given show, prices active on the current saleschannel that can be bought.
 */
export const findPricesByShowId = <ThrowOnError extends boolean = false>(options: Options<FindPricesByShowIdData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindPricesByShowIdResponse, FindPricesByShowIdError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/distribution/salesChannels/{salesChannelId}/shows/{showId}/prices',
        ...options
    });
};

/**
 * Transactions List
 * Get transaction list
 */
export const findTransactions = <ThrowOnError extends boolean = false>(options?: Options<FindTransactionsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindTransactionsResponse, FindTransactionsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/order/transactions',
        ...options
    });
};

/**
 * Entries List
 * Get entries list
 */
export const getEntriesList = <ThrowOnError extends boolean = false>(options?: Options<GetEntriesListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetEntriesListResponse, GetEntriesListError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/order/transactions/tickets/entries',
        ...options
    });
};