// This file is auto-generated by @hey-api/openapi-ts

/**
 * This model is used to describe authorization responses
 */
export type AuthResponse = {
    /**
     * access token value
     */
    accessToken?: string;
    /**
     * expiration duration (in sec)
     */
    expiresIn?: number;
    /**
     * type of authentication
     */
    tokenType?: string;
    /**
     * scope value
     */
    scope?: string;
};

export type EventDetail = {
    /**
     * event identifier
     */
    id?: number;
    /**
     * event name
     */
    name?: string;
    /**
     * event shot name
     */
    shortName?: string;
    /**
     * short description
     */
    presentation1?: string;
    /**
     * event description
     */
    presentation2?: string;
    /**
     * first producer text
     */
    producer1?: string;
    /**
     * second producer text
     */
    producer2?: string;
    /**
     * sponsor text
     */
    sponsor?: string;
    /**
     * category identifier
     */
    categoryId?: number;
    /**
     * subcategory identifier
     */
    subCategoryId?: number;
    /**
     * thumbnail image url
     */
    thumbnail?: string;
    /**
     * cover image url
     */
    cover?: string;
    /**
     * vat percentage of event
     */
    vatPercentage?: string;
    /**
     * keywords of the event
     */
    keywords?: string;
    /**
     * id or url of the facebook event
     */
    facebook?: string;
    prodLicense?: string;
    /**
     * list of external videos
     */
    externalVideos?: string;
    /**
     * minimum age required for event
     */
    minimumAge?: number;
    /**
     * product type of event
     */
    productType?: 'event' | 'pack' | 'subscription';
    /**
     * formatted date of event
     */
    formattedDate?: string;
    /**
     * wallet code of event
     */
    walletCode?: string;
    /**
     * list of holder fields
     */
    holderFields?: Array<{
        /**
         * property name of holder field
         */
        property?: string;
        /**
         * label of holder field
         */
        label?: string;
        /**
         * true if the holder field is required
         */
        required?: boolean;
    }>;
    _links?: {
        self?: Link;
        category?: Link;
        subCategory?: Link;
    };
};

/**
 * This model is used to describe error responses
 */
export type _Error = {
    message?: string;
    code?: number;
    technicalMessage?: string;
    technicalCode?: string;
    technicalParameters?: Array<string>;
    _links?: LinksSelfResponse;
};

export type Error400 = _Error & {
    code?: unknown;
    message?: unknown;
    technicalCode?: unknown;
    technicalMessage?: unknown;
};

export type RouteNotFound = _Error & {
    code?: unknown;
    message?: unknown;
    technicalCode?: unknown;
    technicalMessage?: unknown;
};

export type ResourceNotFound = _Error & {
    code?: unknown;
    message?: unknown;
    technicalCode?: unknown;
    technicalMessage?: unknown;
};

export type LinksSelfResponse = {
    self?: Link;
};

export type LinksPaginationResponse = {
    self?: Link;
    next?: Link;
    prev?: Link;
};

export type Link = {
    href?: string;
};

export type DateTime = {
    date?: string;
    timezone_types?: number;
    timezone?: string;
};

export type Money = {
    /**
     * amounts in cents
     */
    amounts?: string;
    /**
     * currency code
     */
    currency?: string;
};

export type ShowList = {
    _embedded?: {
        /**
         * list of shows
         */
        shows?: Array<Show>;
    };
    _links?: LinksSelfResponse;
};

export type Show = {
    /**
     * show identifier
     */
    id?: number;
    /**
     * start date of show
     */
    start?: string;
    /**
     * end date of show
     */
    end?: string;
    /**
     * default start date of sales for the show
     */
    salesStart?: string;
    /**
     * default end date of sales for the show
     */
    salesEnd?: string;
    /**
     * stock availability status of product in sales channel  - sold_out: product is sold out - in_stock: product is in stock - sold_out_in_cart: product is sold out because last available tickets are in cart (only returned if withSoldOutInCartStatus=true)
     */
    stockAvailabilityStatus?: 'sold_out' | 'in_stock' | 'sold_out_in_cart';
    /**
     * status of sales
     */
    salesStatus?: 'in_sale' | 'finished' | 'pending';
    /**
     * Specified Sales Channel start date, if returned it replace the default sales start date
     */
    specifiedSalesStart?: string;
    /**
     * Specified Sales Channel end date, if returned it replace the default sales end date
     */
    specifiedSalesEnd?: string;
    /**
     * seat choice type
     */
    seatChoiceType?: 'bySeats' | 'bySection' | 'byPrices' | 'mixed';
    /**
     * true if subscription is currently on sale priority
     */
    isSalePriority?: boolean;
    /**
     * true if sale priority is exclusive
     */
    isSalePriorityExclusive?: boolean;
    /**
     * seating map identifier
     */
    seatingMapId?: number;
    /**
     * venue identifier
     */
    venueId?: number;
    _links?: LinksSelfResponse;
};

export type SalesChannelProductList = {
    _embedded?: {
        /**
         * This model describe a sales channel event list
         */
        products?: Array<SalesChannelProductLight>;
    };
    _links?: LinksSelfResponse;
};

export type SalesChannelProductLight = {
    /**
     * product identifier
     */
    id?: number;
    /**
     * organizer identifier
     */
    organizerId?: number;
    /**
     * product name
     */
    name?: string;
    /**
     * presentation text
     */
    presentation1?: string;
    /**
     * detailled presentation text
     */
    presentation2?: string;
    /**
     * url of thumbnail image
     */
    thumbnail?: string;
    /**
     * url of cover image
     */
    cover?: string;
    /**
     * formatted date
     */
    formattedDate?: string;
    /**
     * stock availability status of product in sales channel  - sold_out: product is sold out - in_stock: product is in stock - sold_out_in_cart: product is sold out because last available tickets are in cart (only returned if withSoldOutInCartStatus=true)
     */
    stockAvailabilityStatus?: 'sold_out' | 'in_stock' | 'sold_out_in_cart';
    /**
     * status of sales
     */
    salesStatus?: 'in_sale' | 'finished' | 'pending';
    /**
     * is sale priority
     */
    isSalePriority?: boolean;
    /**
     * is sale priority exclusive
     */
    isSalePriorityExclusive?: boolean;
    /**
     * product type
     */
    productType?: 'event' | 'pack' | 'subscription';
    /**
     * grouping list
     */
    groupingList?: Array<number>;
    _links?: LinksSelfResponse;
};

export type PricesResponse = {
    _embedded?: {
        prices?: Array<PriceLight>;
    };
    _links?: LinksSelfResponse;
};

export type PriceLight = {
    /**
     * price identifier
     */
    id?: number;
    /**
     * price name
     */
    name?: string;
    /**
     * price short name
     */
    shortName?: string;
    /**
     * value in cents
     */
    valueCents?: number;
    /**
     * value without fees in cents
     */
    valueWithoutFeesCents?: number;
    /**
     * required document
     */
    requiredDocument?: string;
    /**
     * true if an access code is required to add the price to the cart
     */
    accessCodeRequired?: boolean;
    /**
     * customer category
     */
    customerCategory?: string;
    /**
     * price type
     */
    priceType?: string;
    /**
     * list of section identifiers
     */
    sectionIdList?: Array<number>;
    /**
     * true if price is exclusive
     */
    isExclu?: boolean;
    /**
     * customer type name
     */
    customerType?: string;
    /**
     * customer type identfier
     */
    customerTypeId?: number;
    /**
     * price category name
     */
    priceCategory?: string;
    /**
     * price category identifer
     */
    priceCategoryId?: number;
    /**
     * list of booking fees
     */
    priceBookingFees?: Array<Fee>;
    /**
     * if has price rule
     */
    hasRule?: boolean;
    /**
     * Minimum quantity per cart
     */
    minQuantityPerCartAddition?: number;
    /**
     * Maximum quantity per cart (0 = unlimited)
     */
    maxQuantityPerCartAddition?: number;
    /**
     * Maximum quantity available
     */
    maxQuantity?: number;
    /**
     * A multiple of the quantity that can be added to the cart
     */
    multipleQuantityPerCartAddition?: number;
    /**
     * define if it trigger the addition of another price
     */
    isAutoAddToCartTrigger?: boolean;
    /**
     * list of required MembershipRules, if not empty a membership is required to add the price to the cart
     */
    requiredMembershipRules?: Array<MembershipRule>;
    /**
     * price complementary data in xml format
     */
    complementXml?: string;
    /**
     * position of the price
     */
    position?: number;
    /**
     * total available entries on price
     */
    totalAvailableSeats?: number;
    _links?: LinksSelfResponse;
};

/**
 * fee object
 */
export type Fee = {
    value?: number;
    vat?: Vat;
    typeCode?: string;
};

/**
 * MembershipRule object
 */
export type MembershipRule = {
    /**
     * membership identifier
     */
    membershipId?: number;
    /**
     * membership name
     */
    membershipName?: string;
    /**
     * quota for membership (0 = unlimited)
     */
    quota?: number;
    /**
     * quota for show
     */
    showQuota?: number;
    /**
     * number of days for membership (0 = unlimited)
     */
    numberOfDays?: number;
    /**
     * true if rename is forbidden
     */
    isRenameForbidden?: boolean;
    _links?: LinksSelfResponse;
};

/**
 * vat object
 */
export type Vat = {
    /**
     * amount in cents
     */
    amountCent?: number;
    percentage?: string;
};

export type TransactionList = {
    _embedded?: {
        /**
         * list of transactions
         */
        transactions?: Array<Transaction>;
    };
    _links?: LinksPaginationResponse;
};

export type Transaction = {
    /**
     * transaction identifier
     */
    id?: number;
    /**
     * bank reference
     */
    refBank?: string;
    purchaseDate?: DateTime;
    /**
     * payement informations
     */
    paymentInfos?: string;
    delivery?: Delivery;
    /**
     * sales channel identifier
     */
    salesChannelId?: number;
    /**
     * currency identifier
     */
    currencyId?: number;
    /**
     * user identifier
     */
    userId?: number;
    /**
     * buyer firstname
     */
    buyerFirstname?: string;
    /**
     * buyer lastname
     */
    buyerLastname?: string;
    /**
     * list of tickets
     */
    tickets?: Array<number>;
    /**
     * list of payments
     */
    payments?: Array<Payment>;
    deliveryAddress?: DeliveryAddress;
    _links?: {
        self?: Link;
        salesChannel?: Link;
    };
};

export type Delivery = {
    /**
     * delivery identifier
     */
    id?: number;
    /**
     * delivery mode name
     */
    name?: string;
    /**
     * delivery amounts in cents
     */
    amountCents?: number;
};

export type Payment = {
    /**
     * payment identifier
     */
    id?: number;
    amountCents?: Money;
    /**
     * payement name
     */
    name?: string;
};

export type DeliveryAddress = {
    label?: string;
    companyName?: string;
    name?: string;
    firstname?: string;
    address?: string;
    additional?: string;
    additional2?: string;
    additional3?: string;
    postOfficeBox?: number;
    city?: string;
    zipCode?: string;
    cedex?: boolean;
    cedexNum?: string;
    civilityId?: number;
    countryFormatId?: number;
};

export type Entry = {
    /**
     * entry identifier
     */
    id?: number;
    /**
     * ticket identifier
     */
    ticketId?: number;
    /**
     * transaction identifier
     */
    transactionId?: number;
    /**
     * seat identifier
     */
    seatId?: number;
    /**
     * seat rank
     */
    seatRank?: string;
    /**
     * seat number
     */
    seatNumber?: string;
    /**
     * gate
     */
    gate?: string;
    /**
     * section name
     */
    sectionName?: string;
    /**
     * show identifier
     */
    showId?: number;
    /**
     * event identifier
     */
    eventId?: number;
    /**
     * price label
     */
    priceLabel?: string;
    /**
     * special label from partner
     */
    placementPartner?: string;
    /**
     * is the ticket printable in PDF ?
     */
    printable?: boolean;
    /**
     * is the ticket visible to end user
     */
    visible?: boolean;
    /**
     * true if ticket has been refund or deleted
     */
    deleted?: boolean;
    /**
     * true if entry has been generated
     */
    generated?: boolean;
    /**
     * detail of last email sent
     */
    lastMailSent?: string;
    /**
     * holder firstname
     */
    holderFirstname?: string;
    /**
     * holder lastname
     */
    holderLastname?: string;
    /**
     * ticket path
     */
    ticketUrl?: string;
    /**
     * delivery mode identifier
     */
    deliveryModeId?: number;
    /**
     * full name of seat
     */
    formatedLabel?: string;
    /**
     * barcode
     */
    barcode?: string;
    /**
     * event name
     */
    eventName?: string;
    showStartDate?: DateTime;
    /**
     * price amount in cents
     */
    priceAmountCents?: number;
    /**
     * buyer firstname
     */
    buyerFirstname?: string;
    /**
     * buyer lastname
     */
    buyerLastname?: string;
    _links?: {
        self?: Link;
        seat?: Link;
    };
};

export type EntriesList = {
    _embedded?: {
        /**
         * list of Entries
         */
        tickets?: Array<Entry>;
    };
    _links?: LinksSelfResponse;
};

export type AuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/authorization/token';
};

export type AuthorizeErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type AuthorizeError = AuthorizeErrors[keyof AuthorizeErrors];

export type AuthorizeResponses = {
    /**
     * Authorization success
     */
    201: AuthResponse;
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type GetEventDetailsData = {
    body?: never;
    path: {
        /**
         * Event identifier
         */
        eventId: number;
    };
    query?: {
        /**
         * Language code identifier ("fr" by default)
         */
        lang?: string;
    };
    url: '/catalog/events/{eventId}';
};

export type GetEventDetailsErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type GetEventDetailsError = GetEventDetailsErrors[keyof GetEventDetailsErrors];

export type GetEventDetailsResponses = {
    /**
     * Sales channel event success
     */
    200: EventDetail;
};

export type GetEventDetailsResponse = GetEventDetailsResponses[keyof GetEventDetailsResponses];

export type FindAllShowByEventAndSalesChannelIdData = {
    body?: never;
    path: {
        /**
         * A saleschannel id must be provided
         */
        salesChannelId: number;
        /**
         * An event id must be provided
         */
        eventId: number;
    };
    query?: {
        /**
         * Maximum number of returned items (page size). Default value is 20, maximum value is 200
         */
        limit?: number;
        /**
         * First offset to return (page position). Default value is 0
         */
        offset?: number;
        /**
         * Language code identifier ("fr" by default)
         */
        lang?: string;
        /**
         * Define show id filters
         */
        'filters[showId][]'?: Array<number>;
        /**
         * Define start event YYYY-MM-DD HH:II:SS
         */
        'filters[dateStart]'?: string;
        /**
         * Define end event YYYY-MM-DD HH:II:SS
         */
        'filters[dateEnd]'?: string;
        /**
         * Define if we want to display sold out in cart status
         */
        withSoldOutInCartStatus?: boolean;
    };
    url: '/distribution/salesChannels/{salesChannelId}/events/{eventId}/shows';
};

export type FindAllShowByEventAndSalesChannelIdErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type FindAllShowByEventAndSalesChannelIdError = FindAllShowByEventAndSalesChannelIdErrors[keyof FindAllShowByEventAndSalesChannelIdErrors];

export type FindAllShowByEventAndSalesChannelIdResponses = {
    /**
     * Get show list success
     */
    200: ShowList;
};

export type FindAllShowByEventAndSalesChannelIdResponse = FindAllShowByEventAndSalesChannelIdResponses[keyof FindAllShowByEventAndSalesChannelIdResponses];

export type FindAllEventBySalesChannelIdData = {
    body?: never;
    path: {
        /**
         * Sales channel identifier
         */
        salesChannelId: number;
    };
    query?: {
        /**
         * Maximum number of returned items (page size). Default value is 20, maximum value is 200
         */
        limit?: number;
        /**
         * First offset to return (page position). Default value is 0
         */
        offset?: number;
        /**
         * Language code identifier ("fr" by default)
         */
        lang?: string;
        /**
         * Filter by grouping id
         */
        'filters[groupingId]'?: number;
        /**
         * Define product id filters
         */
        'filters[productId]'?: number;
        /**
         * Define start event YYYY-MM-DD HH:II:SS
         */
        'filters[dateStart]'?: string;
        /**
         * Define end event YYYY-MM-DD HH:II:SS
         */
        'filters[dateEnd]'?: string;
        /**
         * Define if we want to display sold out in cart status
         */
        withSoldOutInCartStatus?: boolean;
    };
    url: '/distribution/salesChannels/{salesChannelId}/products';
};

export type FindAllEventBySalesChannelIdErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type FindAllEventBySalesChannelIdError = FindAllEventBySalesChannelIdErrors[keyof FindAllEventBySalesChannelIdErrors];

export type FindAllEventBySalesChannelIdResponses = {
    /**
     * Sales channel product list success
     */
    200: SalesChannelProductList;
};

export type FindAllEventBySalesChannelIdResponse = FindAllEventBySalesChannelIdResponses[keyof FindAllEventBySalesChannelIdResponses];

export type FindPricesByShowIdData = {
    body?: never;
    path: {
        /**
         * A sales channel id must be provided
         */
        salesChannelId: number;
        /**
         * A show id must be provided
         */
        showId: number;
    };
    query?: {
        /**
         * Maximum number of returned items (page size). Default value is 20, maximum value is 200
         */
        limit?: number;
        /**
         * First offset to return (page position). Default value is 0
         */
        offset?: number;
        /**
         * Language code identifier ("fr" by default)
         */
        lang?: string;
        /**
         * Define price id filters
         */
        'filters[priceId][]'?: Array<number>;
        /**
         * Define price category id filters
         */
        'filters[priceCategoryId][]'?: Array<number>;
        /**
         * Define customerType id filters
         */
        'filters[customerTypeId][]'?: Array<number>;
        /**
         * Define packLine id filter (only one packLine Id allowed)
         */
        'filters[packLineId]'?: number;
        /**
         * Define seat id filters
         */
        'filters[seatId][]'?: Array<number>;
        /**
         * Define section id filters
         */
        'filters[sectionId][]'?: Array<number>;
        /**
         * define if the prices are in a pack or not - if not specified all prices are returned - If filter packLineId is specified, this filter is forced to true
         */
        'filters[isPackable]'?: boolean;
        /**
         * Define membership id filters
         */
        'filters[membershipId][]'?: Array<number>;
        /**
         * Add pending prices to the response
         */
        addPendingPrices?: boolean;
    };
    url: '/distribution/salesChannels/{salesChannelId}/shows/{showId}/prices';
};

export type FindPricesByShowIdErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type FindPricesByShowIdError = FindPricesByShowIdErrors[keyof FindPricesByShowIdErrors];

export type FindPricesByShowIdResponses = {
    /**
     * Prices success
     */
    200: PricesResponse;
};

export type FindPricesByShowIdResponse = FindPricesByShowIdResponses[keyof FindPricesByShowIdResponses];

export type FindTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of returned items (page size). Default value is 20, maximum value is 200
         */
        limit?: number;
        /**
         * First offset to return (page position). Default value is 0
         */
        offset?: number;
        /**
         * Define event identifier filters
         */
        'filters[eventId][]'?: Array<number>;
        /**
         * Define barcode filter, noting that this may slow down the request due to additional processing.
         */
        'filters[barcode]'?: string;
        /**
         * Define user identifier filter
         */
        'filters[userId][]'?: Array<number>;
        /**
         * Define agent identifier filters
         */
        'filters[agent]'?: string;
        /**
         * Define promoter identifier filters
         */
        'filters[promoterId][]'?: Array<number>;
        /**
         * Define refBank filter
         */
        'filters[refBank]'?: string;
        /**
         * Define transaction id filter
         */
        'filters[transactionId][]'?: Array<number>;
        /**
         * Define deleted filters - If true, only tickets that are deleted are returned - If false or by default, only tickets not deleted are returned
         */
        'filters[deleted]'?: boolean;
        /**
         * Define purchase date filter
         */
        'filters[purchaseDate]'?: string;
        /**
         * Define after purchase date filter
         */
        'filters[afterPurchaseDate]'?: string;
        /**
         * Define sales Channels Id filter
         */
        'filters[salesChannelId][]'?: Array<number>;
        /**
         * Define if the show is ended or not - if true, only tickets where the show is ended are returned - if false, only tickets where the show is not ended are returned
         */
        'filters[isShowEnded]'?: boolean;
        /**
         * Define transaction id sort value (asc or desc). Default is order by transaction id ascendantly. The use of this parameter can significantly slow down the query if no filters are provided. It is recommended to use it with at least two filters.
         */
        'orderBy[id]'?: string;
        /**
         * Define transaction purchaseDate sort value (asc or desc). The use of this parameter can significantly slow down the query if no filters are provided. It is recommended to use it with at least two filters.
         */
        'orderBy[purchaseDate]'?: string;
        /**
         * set to true and set at least one filter by transactionId to use primary connection and avoid replication lag issues
         */
        usePrimaryConnection?: boolean;
    };
    url: '/order/transactions';
};

export type FindTransactionsErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * Route not found, method not allowed
     */
    405: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type FindTransactionsError = FindTransactionsErrors[keyof FindTransactionsErrors];

export type FindTransactionsResponses = {
    /**
     * Get transaction list success
     */
    200: TransactionList;
};

export type FindTransactionsResponse = FindTransactionsResponses[keyof FindTransactionsResponses];

export type GetEntriesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Define event identifier filters
         */
        'filters[eventId][]'?: Array<number>;
        /**
         * Define user identifier filter
         */
        'filters[userId][]'?: Array<number>;
        /**
         * Define transaction identifier filters
         */
        'filters[transactionId][]'?: Array<number>;
        /**
         * Define ticket identifier filters
         */
        'filters[ticketId][]'?: Array<number>;
        /**
         * Define delivery mode filters
         */
        'filters[deliveryModeId][]'?: Array<number>;
        /**
         * if true only entries for ended shows are returned / false for not ended shows / none for all
         */
        'filters[isShowEnded]'?: boolean;
        /**
         * Define deleted filters
         */
        'filters[deleted]'?: boolean;
        /**
         * if true only visible entries are returned
         */
        'filters[onlyVisible]'?: boolean;
        /**
         * Maximum number of returned items (page size). Default value is 20, maximum value is 200
         */
        limit?: number;
        /**
         * First offset to return (page position). Default value is 0
         */
        offset?: number;
    };
    url: '/order/transactions/tickets/entries';
};

export type GetEntriesListErrors = {
    /**
     * An error occurred. Request malformed
     */
    400: Error400;
    /**
     * Authorization error
     */
    401: _Error;
    /**
     * Requested resource not found, no resources found or route not found
     */
    404: ResourceNotFound | RouteNotFound;
    /**
     * Route not found, method not allowed
     */
    405: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
    /**
     * An internal error occurred on remote server
     */
    500: _Error & {
        code?: unknown;
        message?: unknown;
        technicalCode?: unknown;
        technicalMessage?: unknown;
    };
};

export type GetEntriesListError = GetEntriesListErrors[keyof GetEntriesListErrors];

export type GetEntriesListResponses = {
    /**
     * Get entries list success
     */
    200: EntriesList;
};

export type GetEntriesListResponse = GetEntriesListResponses[keyof GetEntriesListResponses];