// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type TokenResponse = {
    authenticationToken?: string | null;
};

export type GetApiTokenTestAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/token/TestAuth';
};

export type GetApiTokenTestAuthErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetApiTokenTestAuthResponses = {
    /**
     * Success
     */
    200: string;
};

export type GetApiTokenTestAuthResponse = GetApiTokenTestAuthResponses[keyof GetApiTokenTestAuthResponses];

export type GetApiTokenByUsernameData = {
    body?: never;
    path: {
        /**
         * partner name
         */
        username: string;
    };
    query?: never;
    url: '/api/token/{username}';
};

export type GetApiTokenByUsernameErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Error
     */
    500: unknown;
};

export type GetApiTokenByUsernameError = GetApiTokenByUsernameErrors[keyof GetApiTokenByUsernameErrors];

export type GetApiTokenByUsernameResponses = {
    /**
     * Success
     */
    200: TokenResponse;
};

export type GetApiTokenByUsernameResponse = GetApiTokenByUsernameResponses[keyof GetApiTokenByUsernameResponses];

export type GetApiByStructureIdTokenByUsernameData = {
    body?: never;
    path: {
        /**
         * structure id
         */
        structureId: number;
        /**
         * partner name
         */
        username: string;
    };
    query?: never;
    url: '/api/{structureId}/token/{username}';
};

export type GetApiByStructureIdTokenByUsernameErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Error
     */
    500: unknown;
};

export type GetApiByStructureIdTokenByUsernameError = GetApiByStructureIdTokenByUsernameErrors[keyof GetApiByStructureIdTokenByUsernameErrors];

export type GetApiByStructureIdTokenByUsernameResponses = {
    /**
     * Success
     */
    200: TokenResponse;
};

export type GetApiByStructureIdTokenByUsernameResponse = GetApiByStructureIdTokenByUsernameResponses[keyof GetApiByStructureIdTokenByUsernameResponses];