#import "./fragments/pageInfoFragment.gql"

query GetEvents($first: Int = 50, $after: String, $ids: [ID!]!) {
  viewer {
    events(first: $first, after: $after, where: { id: { in: $ids } }) {
      edges {
        node {
          id
          name
          state
          startDatetime
          endDatetime
          description
          currency
        }
      }
      pageInfo {
        ...PageInfoFields
      }
      totalCount
    }
  }
}
