// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import type { GetClosingStatementData, GetClosingStatementResponse, GetClosingStatementError, GetClosingStatementsData, GetClosingStatementsResponse, GetClosingStatementsError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

/**
 * Récupération d'un bordereau de clôture
 * Récupération d'un bordereau de clôture
 */
export const getClosingStatement = <ThrowOnError extends boolean = false>(options: Options<GetClosingStatementData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetClosingStatementResponse, GetClosingStatementError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/statement/closing/{id}',
        ...options
    });
};

/**
 * Récupération de bordereaux de clôture
 * Récupération de bordereaux de clôture
 */
export const getClosingStatements = <ThrowOnError extends boolean = false>(options: Options<GetClosingStatementsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetClosingStatementsResponse, GetClosingStatementsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/statement/closing',
        ...options
    });
};